spring:
  mail:
    host: smtp.zoho.com
    username: noreply@meuportaretrato.com
    password: "*F071212f*"
    port: 465
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true